-- AlterTable
ALTER TABLE "LongTermCar" ADD COLUMN     "price1to3" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "price4to6" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "price7plus" DECIMAL(65,30) NOT NULL DEFAULT 0;
